{"83affb372960a2c7e3fea26a11f4abd5":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4278fc1b41a92b53","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ACCAD059B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))","time":{"start":1696047249220,"stop":1696047249220,"duration":0}}]},"6b9d7c6f6e8a7593e536cd856ae58af1":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"71a2c1fdd17c05a3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ACCB04B828>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))","time":{"start":1696047258903,"stop":1696047258903,"duration":0}}]}}