{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ACCAD059B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))","children":[{"name":"test_login1","uid":"4278fc1b41a92b53","parentUid":"844a6ea35f1059f32aa244183b18294e","status":"broken","time":{"start":1696047249220,"stop":1696047249220,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"844a6ea35f1059f32aa244183b18294e"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ACCB04B828>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))","children":[{"name":"test_login2","uid":"71a2c1fdd17c05a3","parentUid":"8a9c6b2b6c2084be33a80b24c7f26028","status":"broken","time":{"start":1696047258903,"stop":1696047258903,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"8a9c6b2b6c2084be33a80b24c7f26028"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}